FROM public.ecr.aws/lambda/nodejs:18

# Install compilers
RUN yum -y install gcc gcc-c++ python3 java-devel

# Set working directory
WORKDIR /var/task

# Copy function code
COPY app.js .

# Create package.json and install uuid
RUN npm init -y && npm install uuid

# Set CMD
CMD ["app.handler"]